version: '3.5'
services:
  postgres-server:   
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./env_vars/.env_db_pgsql

    networks:
      zbx_net_backend:
        # ipv4_address: 172.16.239.101
    volumes:
      - /home/ubuntu/zabbix/zabbix-database/database:/var/lib/postgresql/data:rw
      - ./zbx_env/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ./zbx_env/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ./zbx_env/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
  zabbix-server:    
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      # - snmptraps:/var/lib/zabbix/snmptraps:rw
    networks:
      zbx_net_backend:
      zbx_net_frontend:
        # ipv4_address: 172.16.239.102
    ports:
      - 10051:10051

    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_srv
    depends_on:
      - postgres-server

  
  zabbix-web:   
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    restart: always
    user: root
    # command: bash -c "
    #       apk add ldb-dev libldap openldap-dev
    #         "
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro  
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_web
    networks:
      zbx_net_backend:
        # ipv4_address: 172.16.239.103
      zbx_net_frontend:
        # ipv4_address: 172.16.238.101

    ports:
      - 80:8080

    depends_on:
      - postgres-server
      - zabbix-server
  

  zabbix-agent:   
    image: zabbix/zabbix-agent:alpine-6.0-latest
    privileged: true 
    # network_mode: "host"
    restart: unless-stopped
    env_file:
      - ./env_vars/.env_agent
    networks:
      zbx_net_backend:
        ipv4_address: 172.16.239.104

    # environment:
    #   - ZBX_SERVER_HOST=127.0.0.1 #the IP/Dns of Zabbix server
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.0-latest
    networks:
      zbx_net_backend:
        # ipv4_address: 172.16.239.105
    ports:
      - 10052:10052
# networks:
#  zbx_net:
#    driver: bridge

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.16.239.0/24"
# /home/ubuntu/zabbix/zabbix-database/database
# /dev/mapper/database--volume-database




