  
version: '3.5'
services:
  zabbix-agent:   
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    privileged: true 
    ports:
      - 10050:10050
    restart: unless-stopped
    env_file:
      - .env_agent
    volumes:
      - ./certs/:/root/
